2082/05/23  11:33 AM, @CWRS, Pulchowk Campus

[NumPy](https://numpy.org/doc/2.3/user/absolute_beginners.html)

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.shape

(2, 3)

# Why use NumPy?
Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

# What is an “array”?
In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

## Most NumPy arrays have some restrictions. For instance:

All elements of the array must be of the same type of data.

Once created, the total size of the array can’t change.

The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[0]

np.int64(1)

In [6]:
# Array are mutable
a[0]=15
a

array([15,  2,  3,  4,  5,  6])

In [7]:
a[:3]

array([15,  2,  3])

In [8]:
b = a[3:]

In [9]:
b

array([4, 5, 6])

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[1,2]
# Column number at last and row number at second last

np.int64(7)

In [12]:
a.ndim

2

In [13]:
a.shape

(3, 4)

In [14]:
a.size

12

In [15]:
import math

In [16]:
a.size == math.prod(a.shape)

True

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.

In [17]:
a.dtype

dtype('int64')

How to create a basic array

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 3.22648102e-307,
       2.46084266e-317])

In [21]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [22]:
np.linspace(0,10, 10)
# Here the last argument is number of elements that we want between the start and end .. 10 means 10 number of point between 0 and 10 which will idvede the sace into 9 equal division

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
x = np.ones(2,dtype=np.int64)

In [24]:
x

array([1, 1])

Adding, removing, and sorting elements

In [25]:
arr = np.array([1,2,3,10,4,5,11,6,7,0,8,9])

In [26]:
np.sort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [28]:
np.concatenate((a,b),)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [30]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Shape and Size of an Array

In [31]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [32]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [33]:
array_example.ndim

3

In [34]:
array_example.size

24

In [35]:
array_example.shape

(3, 2, 4)

Reshaping an Array

** If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [36]:
a = np.arange(6)

In [37]:
a

array([0, 1, 2, 3, 4, 5])

In [38]:
b = a.reshape(3,2)

In [39]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
np.reshape(a, shape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

Converting a 1D array into a 2D array

In [41]:
a = np.array(np.random.rand(6))

In [42]:
a

array([0.33621222, 0.59094944, 0.75727149, 0.91148183, 0.37141596,
       0.7561249 ])

In [43]:
a2 = a[np.newaxis, :]

In [44]:
a2

array([[0.33621222, 0.59094944, 0.75727149, 0.91148183, 0.37141596,
        0.7561249 ]])

Indexing and Slicing

In [45]:
data = np.array([1,2,3,4,5,6,7,8,9])

In [46]:
print(data[data<2])

[1]


# 2082/06/02  03:47 PM, @ CWRS, IOE, Pulchowk Campus

[Link to documentation](https://numpy.org/doc/2.3/user/absolute_beginners.html#:~:text=You%20can%20select%20elements%20that%20are%20divisible%20by%202%3A)

In [48]:
a = np.array([1,2,3,4,5,6,7,8,9])

divisible_by_2 = a[a%2 ==0]
print(divisible_by_2)

[2 4 6 8]


In [50]:
c=a[(a>2) & (a<7)]
c

array([3, 4, 5, 6])

In [51]:
five_up = (a>5) | (a==5)

In [52]:
five_up

array([False, False, False, False,  True,  True,  True,  True,  True])

In [53]:
b = np.nonzero(a<5)
b

(array([0, 1, 2, 3]),)

In [55]:
# list_of_coordinates = list(zip(b[0],b[1]))

# for cord in list_of_coordinates:
#     print(cord)

# How to create an array from existing data

In [56]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [57]:
ar1 = a[3:8]

In [58]:
ar1

array([4, 5, 6, 7, 8])

In [60]:
a1 = np.array([[1,1],
              [2,2]])
a2 = np.array([[3,3],
              [4,4]])

In [61]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [62]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [63]:
x = np.arange(1,25).reshape(2,12)

In [64]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [65]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [68]:
np.hsplit(x,(3,6))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [69]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [70]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
data = np.ones(2,dtype=np.int32)

In [75]:
data

array([1, 1], dtype=int32)

In [84]:
data = np.array([1,2])
ones = np.ones(2, dtype = int)
data + ones


array([2, 3])

In [80]:
data - ones

array([0, 1])

In [85]:
data*data

array([1, 4])

In [86]:
data.sum()

np.int64(3)

# Broadcasting