2082/05/23  11:33 AM, @CWRS, Pulchowk Campus

[NumPy](https://numpy.org/doc/2.3/user/absolute_beginners.html)

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

# Why use NumPy?
Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

# What is an “array”?
In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

## Most NumPy arrays have some restrictions. For instance:

All elements of the array must be of the same type of data.

Once created, the total size of the array can’t change.

The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [5]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a[0]

np.int64(1)

In [9]:
# Array are mutable
a[0]=15
a

array([15,  2,  3,  4,  5,  6])

In [10]:
a[:3]

array([15,  2,  3])

In [12]:
b = a[3:]

In [13]:
b

array([4, 5, 6])

In [14]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
a[1,2]
# Column number at last and row number at second last

np.int64(7)

In [17]:
a.ndim

2

In [18]:
a.shape

(3, 4)

In [19]:
a.size

12

In [20]:
import math

In [21]:
a.size == math.prod(a.shape)

True

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.

In [22]:
a.dtype

dtype('int64')

How to create a basic array

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
np.empty(5)

array([0.00000000e+000, 9.31429229e-312, 0.00000000e+000, 9.30495154e-312,
       0.00000000e+000])

In [27]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [29]:
np.linspace(0,10, 10)
# Here the last argument is number of elements that we want between the start and end .. 10 means 10 number of point between 0 and 10 which will idvede the sace into 9 equal division

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
x = np.ones(2,dtype=np.int64)

In [31]:
x

array([1, 1])

Adding, removing, and sorting elements

In [34]:
arr = np.array([1,2,3,10,4,5,11,6,7,0,8,9])

In [35]:
np.sort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [37]:
np.concatenate((a,b),)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [42]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Shape and Size of an Array

In [43]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [44]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [45]:
array_example.ndim

3

In [46]:
array_example.size

24

In [47]:
array_example.shape

(3, 2, 4)

Reshaping an Array

** If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [48]:
a = np.arange(6)

In [49]:
a

array([0, 1, 2, 3, 4, 5])

In [50]:
b = a.reshape(3,2)

In [51]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
np.reshape(a, shape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

Converting a 1D array into a 2D array

In [53]:
a = np.array(np.random.rand(6))

In [54]:
a

array([0.47039048, 0.98386047, 0.5265846 , 0.10552172, 0.16282183,
       0.23753147])

In [55]:
a2 = a[np.newaxis, :]

In [56]:
a2

array([[0.47039048, 0.98386047, 0.5265846 , 0.10552172, 0.16282183,
        0.23753147]])